name: Docker Check

on:
  pull_request:

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 BuildKit Docker container builder，支持多平台镜像构建和缓存
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # 构建 Docker 镜像
      # 注意：在检查步骤中，不会推送镜像
      - name: Build Docker image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: false  # 在检查过程中不会推送镜像
          tags: temp-check-image  # 使用临时标签进行构建
          labels: temp-check-label  # 使用临时标签
          cache-from: type=gha
          cache-to: type=gha,mode=max

